### PR TITLE
Refactor levels closes #31

### LINKED ISSUE #31: Refactor levels

### PR DESCRIPTION
**Pull request by livecodelife**
What's this PR do?
Refactors the creation of obstacles and targets in each level into functions

Where should the reviewer start?

lib/level_one.js

How should this be manually tested?

Run the game, levels are still created with obstacles and targets

Any background context you want to provide?

Screenshots (if appropriate)

What gif best describes this PR or how it makes you feel?

[Done](https://media.giphy.com/media/kixtPnJ5a7A7S/giphy.gif)

@zackforbing @neight-allen

### CODE REVIEW

**Review by neight-allen — CHANGES_REQUESTED** [review]
I like the consistent pattern, but I'm not sure how this is better.  Lines 18 and 20 in `level_two.js` are now super long, hard to read, and thus hard to maintain. What if you had a `levels` object. Something like:

``` js
levels = [
  obstacles: [
    {x: 350, y: 100}
  ],
  targets: [
    {x: 855, y: 250}
  ]
]
```

And then iterate over that in one `levels.js` file

**Comment by zackforbing** [comment]
I think you were on the right track by creating functions to encompass obstacle and target creation!

**Review by neight-allen — COMMENTED** [review]
I think this is better than it was, but I question the value of having these as functions. As in, if you just moved the return arrays into the constructor, I think it would work just as well.

Also, put each new `Target` and `Obstacle` constructor on it's own line. Too hard to read all in one line.

**Comment by neight-allen** [comment]
Did you mean to include all of the tests in this PR? It's unclear to me whether that was related to your refactor.

**Pull request merged**
